/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ray' at '1/24/16 8:20 PM' with Gradle 2.6
 *
 * @author ray, @date 1/24/16 8:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
